fix: add run_identity parameter to _save_to_cohort and callers
The previous commit added run_identity to log_comparison but forgot to
add it to _save_to_cohort which is called internally. This caused a
NameError: name 'run_identity' is not defined.